# Generated by Django 3.2.3 on 2021-06-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('available', models.BooleanField(default=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('services', models.CharField(blank=True, max_length=255, null=True)),
                ('home_type', models.PositiveSmallIntegerField(choices=[(0, 'Casa'), (1, 'departamento'), (2, 'PH'), (3, 'Duplex')], default=0)),
                ('rooms', models.PositiveSmallIntegerField(default=1, null=True)),
                ('bathroom', models.PositiveSmallIntegerField(default=1, null=True)),
                ('bedroom', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('garage', models.BooleanField(default=False)),
                ('total_surface', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('covered_area', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Exelente'), (1, 'Muy bueno'), (2, 'Bueno'), (3, 'A reparar')], default=1)),
                ('ages', models.PositiveSmallIntegerField(blank=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='propiedades')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
