# Generated by Django 3.2.3 on 2023-03-18 20:54

from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('home_type', models.PositiveSmallIntegerField(choices=[(0, 'Casa'), (1, 'departamento'), (2, 'PH'), (3, 'Duplex')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=properties.models.get_image_path)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
