# Generated by Django 3.2.3 on 2023-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_image_mymodelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='home_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Casa'), (1, 'departamento'), (2, 'PH'), (3, 'Duplex')], default=0),
        ),
    ]
